version: '3'

services:
  cicd-backend:
    build: 
      context: .
      dockerfile: Dockerfile 
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - '8001:8001'
    restart: always
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn core.wsgi:application --bind 0.0.0.0:8001"
    networks:
      - nginx_network

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - /var/jenkins_home/workspace/test_pipeline/nginx_conf.d:/etc/nginx/conf.d
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - cicd-backend
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge


volumes:
  static_volume:
  media_volume: